---
title: "Introduction"
author: "Truong Phi"
---

## Overview

The **Positional Burrows-Wheeler Transform (PBWT)**, introduced by Richard Durbin in 2014 [@durbinEfficientHaplotypeMatching2014], is an efficient and scalable data structure for handling large haplotype datasets. It has been applied in many important genomic tasks:

- Phasing haplotypes [@browningFastTwostagePhasing2021a] 
- Genotype imputation [@rubinacciImputationLowcoverageSequencing2023a;@rubinacciGenotypeImputationUsing2020]
- Identifying identical-by-descent (IBD) segments [@naseriRaPIDUltrafastPowerful2019]
- Pangenomic haplotype analysis [@baaijensComputationalGraphPangenomics2022]

### Motivation

The PBWT algorithm is powerful, yet it can be challenging for newcomers to grasp. I am grateful for Alistair Miles's insightful [blog post](https://alimanfoo.github.io/2016/06/21/understanding-pbwt.html), which provides a practical bridge between Richard Durbin's original paper and a working implementation. 

However, there is still a need for a deeper intuition of the underlying processes and how they were implemented in practice. I created this blog to provide mental models of how PBWT algorithms function. By analyzing [Richard Durbin's source code](https://github.com/richarddurbin/pbwt), I have developed simplified pseudo-code that captures the core logic and created illustrative algorithmic diagrams to visualize how the algorithms are implemented with a specific example.

### Content covered

*   **Construction:** How to build prefix and divergence arrays ([Algorithms 1&2](./pbwt-core/algorithm_12.qmd)).
*   **Internal Matching:** Identifying shared segments and maximal matches within a population:
    - [Algorithms 2&3](./pbwt-core/algorithm_23.qmd): Report matches longer than $L$
    - [Algorithms 2&4](./pbwt-core/algorithm_24.qmd): Report set maximal matches
*   **External Querying:** Mapping a new haplotype against a PBWT database ([Algorithm 2&5](./pbwt-core/algorithm_25.qmd)).





::: {#refs style="margin-top: 6.5rem;"}
---
:::