project:
  type: website
  output-dir: _site

bibliography: assets/bibliography.bib

website:
  page-navigation: true
  title: "PBWT Blog"
  description: Clearly illustrate PBWT algorithms
  repo-url: https://github.com/Truongphi20/pbwt
  favicon: assets/logo.png
  open-graph: true
    
  sidebar:
    logo: assets/logo.png
    style: "docked"
    tools: 
      - icon: github
        href: https://github.com/Truongphi20/pbwt
        text: "GitHub repo"
      - icon: person-fill
        text: "Phi Nguyen Truong"
        href: https://truongphi20.github.io/
    search: true
    collapse-level: 1
    contents:
      - href: posts/introduction.qmd
        text: Introduction
      - section: "Core algorithms"
        contents:
          - posts/pbwt-core/algorithm_12.qmd
          - posts/pbwt-core/algorithm_23.qmd
          - posts/pbwt-core/algorithm_24.qmd
          - posts/pbwt-core/algorithm_25.qmd
      - href: posts/summary.qmd
        text: Summary

format:
  html:
    theme:
      light: [cosmo, assets/theme.scss]
      dark: [cosmo, assets/theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    grid:
      sidebar-width: 400px

freeze: auto